### PR TITLE
Throw an exception if FAT bytes per sector is 0

### LINKED ISSUE #152: DivideByZeroException reading (invalid?) FAT32 image
```
            using (Stream stream = File.OpenRead(@"C:\Users\Adam\Desktop\fat-test.img"))
            {
                Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                DiscUtils.Fat.FatFileSystem fat = new FatFileSystem(stream);
                Console.WriteLine(fat.VolumeLabel);
            }
```
Throws a DivideByZeroException.

```
at DiscUtils.Fat.FatFileSystem.DetectFATType(Byte[] bpb)
at DiscUtils.Fat.FatFileSystem.Initialize(Stream data)
at DiscUtils.Fat.FatFileSystem..ctor(Stream data)
```

Was attempting to read 2019-04-08-raspbian-stretch-lite.img (https://downloads.raspberrypi.org/raspbian_lite_latest) which contains a FAT32 partition at the start of the image. Yes, DiscUtils should probably throw me out at this point, but DivideByZero isn't the exception I was expecting.

Edit: right, seeking to 0x400000h, copying to another stream and then reading from there works. I suspect I could use DiscUtils partiton functions to do this for me - but calling `new FatFileSystem` seems to seek back to 0 in the Stream, then crash. Should I raise another bug for this?

### PR DESCRIPTION
**Pull request by voltagex**
Closes #152

### CODE REVIEW

File: Tests/LibraryTests/Fat/FatFileSystemTest.cs [hunk 1]
```diff
@@ -228,7 +228,15 @@ public void HonoursReadOnly()
...
                 fileStream.ReadByte();
             }
+        }
 
+        [Fact]
+        public void InvalidImageThrowsException()
+        {
+            SparseMemoryStream stream = new SparseMemoryStream();
+            byte[] buffer = new byte[1024 * 1024];
+            stream.Write(buffer, 0, 1024 * 1024);
```
Comment (LordMike) [inline Tests/LibraryTests/Fat/FatFileSystemTest.cs]: Remember to seek back to beginning
